services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #      - MYSQL_USER=root
      #      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_HOST=%
#    volumes:
#      - ./data/mysql:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - cloud-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

networks:
  cloud-network:
    driver: bridge
  spring:
    driver: bridge